---
- name: Setup Kubernetes Cluster
  hosts: k3s_cluster
  become: yes
  tasks:
    - name: Update and Upgrade APT
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - containerd
        state: present

    - name: Add Kubernetes signing key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Add Kubernetes APT repository
      apt_repository:
        repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
        state: present

    - name: Install Kubernetes packages
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present

    - name: Disable swap
      command: swapoff -a
      when: ansible_os_family == "Debian"

    - name: Remove swap from fstab
      lineinfile:
        path: /etc/fstab
        regexp: '.*swap.*'
        state: absent

    - name: Enable bridging
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        state: present
        reload: yes

    - name: Enable br_netfilter
      modprobe:
        name: br_netfilter
        state: present

    - name: Reboot the server
      reboot:

- name: Initialize Kubernetes Cluster
  hosts: master[0]
  become: yes
  tasks:
    - name: Initialize the cluster
      command: kubeadm init --control-plane-endpoint={{ groups['master'][0] }} --pod-network-cidr=10.244.0.0/16
      when: inventory_hostname == groups['master'][0]

    - name: Create a token and retrieve its hash
      shell: |
        TOKEN=$(kubeadm token create)
        HASH=$(openssl x509 -pubkey -in /etc/kubernetes/pki/ca.crt | openssl rsa -pubin -outform der 2>/dev/null | openssl dgst -sha256 -hex | sed 's/^.* //')
        echo "token: $TOKEN" > /tmp/kubeadm_token_hash
        echo "hash: $HASH" >> /tmp/kubeadm_token_hash
      when: inventory_hostname == groups['master'][0]
      register: kubeadm_token_hash

    # - name: Fetch kubeadm_token_hash from master[0]
    #   fetch:
    #     src: /tmp/kubeadm_token_hash
    #     dest: /tmp/kubeadm_token_hash
    #   when: inventory_hostname == groups['master'][0]

    - name: Synchronize kubeadm_token_hash to other nodes
      synchronize:
        src: /tmp/kubeadm_token_hash
        dest: /tmp/kubeadm_token_hash
      delegate_to: "{{ item }}"
      with_items: "{{ groups['k3s_cluster'] }}"

    - name: Copy kube config file to user's home directory
      shell: |
        mkdir -p $HOME/.kube &&
        cp -i /etc/kubernetes/admin.conf $HOME/.kube/config &&
        chown $(id -u):$(id -g) $HOME/.kube/config
      when: inventory_hostname == groups['master'][0]

    - name: Copy kubeadm_token_hash to other nodes
      copy:
        src: /tmp/kubeadm_token_hash
        dest: /tmp/kubeadm_token_hash
      delegate_to: "{{ item }}"
      with_items: "{{ groups['k3s_cluster'] }}"

- name: Join Nodes to Cluster
  hosts: master[1:2]
  become: yes
  tasks:
    - name: Retrieve token and hash
      shell: cat /tmp/kubeadm_token_hash
      register: kubeadm_token_hash

    - name: Join master nodes to cluster
      command: "kubeadm join {{ groups['master'][0] }}:6443 --token {{ kubeadm_token_hash.stdout_lines[0].split(': ')[1] }} --discovery-token-ca-cert-hash {{ kubeadm_token_hash.stdout_lines[1].split(': ')[1] }} --control-plane"
      when: inventory_hostname in groups['master']

- name: Join Worker Nodes to Cluster
  hosts: node
  become: yes
  tasks:
    - name: Retrieve token and hash
      shell: cat /tmp/kubeadm_token_hash
      register: kubeadm_token_hash

    - name: Join worker nodes to cluster
      command: "kubeadm join {{ groups['master'][0] }}:6443 --token {{ kubeadm_token_hash.stdout_lines[0].split(': ')[1] }} --discovery-token-ca-cert-hash {{ kubeadm_token_hash.stdout_lines[1].split(': ')[1] }}"
      when: inventory_hostname in groups['node']

- name: Install Network Plugin
  hosts: master[0]
  become: yes
  tasks:
    - name: Install Flannel
      command: kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml
      when: inventory_hostname == groups['master'][0]
