---
- name: Install HAProxy
  hosts: haproxy
  become: yes
  tasks:
    - name: Install HAProxy
      apt:
        name: haproxy
        state: present

    - name: Copy HAProxy configuration
      copy:
        src: haproxy.cfg
        dest: /etc/haproxy/haproxy.cfg
      notify:
        - Restart HAProxy

    - name: Allow user to run haproxy without password
      lineinfile:
        path: /etc/sudoers.d/haproxy
        line: 'serveradmin ALL=(ALL:ALL) NOPASSWD: /usr/sbin/haproxy'
        create: yes

    - name: Validate sudoers file
      command: visudo -cf /etc/sudoers.d/haproxy

  handlers:
    - name: Restart HAProxy
      systemd:
        name: haproxy
        state: restarted
