---
- name: Install K3s Worker Nodes
  hosts: node
  become: true
  tasks:
    - name: Create config directory
      file:
        path: /etc/rancher/k3s
        state: directory

    - name: Create token file
      copy:
        content: "supersecrettoken"
        dest: /etc/rancher/k3s/cluster-token

    - name: Create kubelet configuration file
      copy:
        src: kubelet.config
        dest: /etc/rancher/k3s/kubelet.config

    - name: Create K3s config file
      template:
        src: k3s_config_worker.yaml.j2
        dest: /etc/rancher/k3s/config.yaml

    - name: Install agent node
      shell: "curl -sfL https://get.k3s.io | sh -s - agent --server https://kube-haproxy.home:6443"
